	VideoBox u0 (
		.led_bus_export     (<connected-to-led_bus_export>),     //     led_bus.export
		.memory_mem_a       (<connected-to-memory_mem_a>),       //      memory.mem_a
		.memory_mem_ba      (<connected-to-memory_mem_ba>),      //            .mem_ba
		.memory_mem_ck      (<connected-to-memory_mem_ck>),      //            .mem_ck
		.memory_mem_ck_n    (<connected-to-memory_mem_ck_n>),    //            .mem_ck_n
		.memory_mem_cke     (<connected-to-memory_mem_cke>),     //            .mem_cke
		.memory_mem_cs_n    (<connected-to-memory_mem_cs_n>),    //            .mem_cs_n
		.memory_mem_ras_n   (<connected-to-memory_mem_ras_n>),   //            .mem_ras_n
		.memory_mem_cas_n   (<connected-to-memory_mem_cas_n>),   //            .mem_cas_n
		.memory_mem_we_n    (<connected-to-memory_mem_we_n>),    //            .mem_we_n
		.memory_mem_reset_n (<connected-to-memory_mem_reset_n>), //            .mem_reset_n
		.memory_mem_dq      (<connected-to-memory_mem_dq>),      //            .mem_dq
		.memory_mem_dqs     (<connected-to-memory_mem_dqs>),     //            .mem_dqs
		.memory_mem_dqs_n   (<connected-to-memory_mem_dqs_n>),   //            .mem_dqs_n
		.memory_mem_odt     (<connected-to-memory_mem_odt>),     //            .mem_odt
		.memory_mem_dm      (<connected-to-memory_mem_dm>),      //            .mem_dm
		.memory_oct_rzqin   (<connected-to-memory_oct_rzqin>),   //            .oct_rzqin
		.ref_clock_clk      (<connected-to-ref_clock_clk>),      //   ref_clock.clk
		.sdram_bus_addr     (<connected-to-sdram_bus_addr>),     //   sdram_bus.addr
		.sdram_bus_ba       (<connected-to-sdram_bus_ba>),       //            .ba
		.sdram_bus_cas_n    (<connected-to-sdram_bus_cas_n>),    //            .cas_n
		.sdram_bus_cke      (<connected-to-sdram_bus_cke>),      //            .cke
		.sdram_bus_cs_n     (<connected-to-sdram_bus_cs_n>),     //            .cs_n
		.sdram_bus_dq       (<connected-to-sdram_bus_dq>),       //            .dq
		.sdram_bus_dqm      (<connected-to-sdram_bus_dqm>),      //            .dqm
		.sdram_bus_ras_n    (<connected-to-sdram_bus_ras_n>),    //            .ras_n
		.sdram_bus_we_n     (<connected-to-sdram_bus_we_n>),     //            .we_n
		.sdram_clock_clk    (<connected-to-sdram_clock_clk>),    // sdram_clock.clk
		.vga_bus_CLK        (<connected-to-vga_bus_CLK>),        //     vga_bus.CLK
		.vga_bus_HS         (<connected-to-vga_bus_HS>),         //            .HS
		.vga_bus_VS         (<connected-to-vga_bus_VS>),         //            .VS
		.vga_bus_BLANK      (<connected-to-vga_bus_BLANK>),      //            .BLANK
		.vga_bus_SYNC       (<connected-to-vga_bus_SYNC>),       //            .SYNC
		.vga_bus_R          (<connected-to-vga_bus_R>),          //            .R
		.vga_bus_G          (<connected-to-vga_bus_G>),          //            .G
		.vga_bus_B          (<connected-to-vga_bus_B>)           //            .B
	);

